
const faker = require('faker');
const users = [
    {
        id: 1,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 2,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 3,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 4,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 5,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 6,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 7,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 8,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 9,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 10,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 11,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 12,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 13,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 14,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 15,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        id: 16,
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
    {
        firstName: faker.name.firstName(),
        lastName: faker.name.lastName(),
        // profilePicture: faker.image.avatar(),
        email: faker.internet.email(),
        // phone: faker.phone.phoneNumber(),
        // bio: faker.lorem.paragraph(),
        // jobTitle: faker.name.jobTitle(),
        // adress: faker.address.city(),
        // country: faker.address.country(),
        // randomNumber: faker.random.number(),
        date: faker.date.recent(),
        // created_at: faker.date.past(),
    },
]
exports.users = users;